language: rust
os:
    - linux
    - osx
env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
install:
    - curl -O http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz
    - tar xfz pa_stable_v19_20140130.tgz
    - (cd portaudio/ && ./configure && make && sudo make install)
before_script:
    - rustc -v
    - cargo -V
script:
    - cargo build -v
    - cargo test -v
