[package]

name = "rust-dsp"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "indiv0 <contact@nikitapek.in>",
    "mitchmindtree <mitchell.nordine@gmail.com>"
]

[lib]

name = "dsp"
path = "./src/lib.rs"

[dependencies.sound_stream]
git = "https://github.com/mitchmindtree/sound_stream"

