[package]

name = "rust-dsp"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "indiv0 <contact@nikitapek.in>",
    "mitchmindtree <me@michellnordine.com>"]

[[lib]]

name = "dsp"
path = "./src/lib.rs"

[dependencies.rust-portaudio]

git = "https://github.com/jeremyletang/rust-portaudio"

