[package]

name = "dsp-chain"
version = "0.3.0"
authors = [
    "mitchmindtree <mitchell.nordine@gmail.com>",
    "bvssvni <bvssvni@gmail.com>",
    "indiv0 <contact@nikitapek.in>"
]
description = "Provides a trait for chaining together audio elements in a node-system."
readme = "README.md"
keywords = ["audio", "dsp", "io", "modular", "stream"]
license = "MIT"
repository = "https://github.com/RustAudio/dsp-chain.git"
homepage = "https://github.com/RustAudio/dsp-chain"


[lib]

name = "dsp"
path = "./src/lib.rs"

[dependencies]
sound_stream = "*"
