[package]

name = "rust-dsp"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "indiv0 <contact@nikitapek.in>",
    "mitchmindtree <mitchell.nordine@gmail.com>"
]

[lib]

name = "dsp"
path = "./src/lib.rs"

[dependencies.rust-portaudio]
git = "https://github.com/jeremyletang/rust-portaudio"

[dependencies.time]
git = "https://github.com/rust-lang/time"

[[bin]]

name = "test"
path = "./src/test.rs"
